- name: Build Container Image
  run: |
    podman build \
      -f Calculator-Dockerfile \
      -t ghcr.io/${{ github.repository_owner }}/online-calc:${{ github.sha }} \
      .

- name: Push Container Image
  run: |
    podman push \
      ghcr.io/${{ github.repository_owner }}/online-calc:${{ github.sha }}
