name: Build and Deploy Calculator

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        run: |
          podman login ghcr.io \
            -u "${{ github.actor }}" \
            -p "${{ secrets.GITHUB_TOKEN }}"

      - name: Build Container Image
        run: |
          podman build \
            -f Calculator-Dockerfile \
            -t ghcr.io/${{ github.repository_owner }}/online-calc:${{ github.sha }} \
            .

      - name: Push Container Image
        run: |
          podman push \
            ghcr.io/${{ github.repository_owner }}/online-calc:${{ github.sha }}

      - name: Login to OpenShift
        run: |
          oc login "${{ secrets.OPENSHIFT_API }}" \
            --token="${{ secrets.OPENSHIFT_TOKEN }}" \
            --insecure-skip-tls-verify=true

      - name: Deploy Calculator
        run: |
          oc project openshiftdemo
          oc set image deployment/online-calc \
            online-calc=ghcr.io/${{ github.repository_owner }}/online-calc:${{ github.sha }}
          oc rollout status deployment/online-calc
